permalink:           pretty

# Setup
title:               David's Blog
tagline:             'A graduate student in Computer Science'
description:         ''
url:                 http://youchen.me
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              David
  url:               https://youchen.me
  email:             youchen.du(at)gmail.com
repo-link:           https://github.com/Time1ess/Time1ess.github.io

# Gems module
gems:                [jekyll-paginate]

# Custom settings
comments:            true
